name: "💡 Feature request"
description: Suggest an idea for this project
title: "[feat]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear and concise description of what the feature request is. Please include if your feature request is related to a problem
    validations:
      required: true